### PR TITLE
HPOT-35: Local or Global Identification

### PR DESCRIPTION
**Pull request by Boykinmr**
implemented ipaddress module and added getLocalRemote function to env.py.  changed ssh, telnet tables and generic.py files to add localRemote to connections table.  Let me know if we don't want to change the tables so I can change it to just pass a string instead and we can change the developer tag to get that.

### CODE REVIEW

**Comment by Jeff-Rowell** [comment]
The GraphQL code needs to be updated as well with respect these changes.

**Comment by Jeff-Rowell** [comment]
On second thought, I do not know if adding a column for whether an IP is local or remote in the database is helpful, because we can just look at the IP address and determine that information. Seems like a redundant column that isn't needed.

**Comment by Boykinmr** [comment]
I asked Dr. Beaty and Tyler if they wanted this to be in the tables "connections" or if it is to be a function that was set up for when they want to upload the information and they didn't have a preference.  I'll work on the GraphQL.

**Comment by Jeff-Rowell** [comment]
Modified the GraphQL tests to respect the new column added. Re-ran the tests and verified that all GraphQL tests pass and still at 100% code coverage.

**Comment by Jeff-Rowell** [comment]
**Note:** When running this branch it expects a fresh db, so the HPotter/hpotter-server/main.db file will either need to be moved or deleted before running the code.

**Pull request merged**
